# =============================================================================
# SIMCOMP — Inventario Ansible
# 3 VMs — red privada 192.168.100.x
# Para ansible_local usamos 127.0.0.1 para evitar problemas de red interna.
# =============================================================================

[dns_servers]
svr-dns ansible_host=127.0.0.1 ansible_connection=local

[api_servers]
svr-api ansible_host=127.0.0.1 ansible_connection=local

[web_servers]
svr-web ansible_host=127.0.0.1 ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'