# =============================================================================
# SIMCOMP — Inventario Ansible
# 3 VMs — red privada 192.168.100.x
# =============================================================================

[svr-dns]
192.168.100.2 ansible_user=vagrant ansible_ssh_private_key_file=/vagrant/.vagrant/machines/svr-dns/virtualbox/private_key

[svr-api]
192.168.100.3 ansible_user=vagrant ansible_ssh_private_key_file=/vagrant/.vagrant/machines/svr-api/virtualbox/private_key

[svr-web]
192.168.100.4 ansible_user=vagrant ansible_ssh_private_key_file=/vagrant/.vagrant/machines/svr-web/virtualbox/private_key

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'