version: "3.8"

services:
  postgres:
    #image: postgres:16                     # Usar para docker
    image: docker.io/library/postgres:16    # Usar para podman
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  ms-auth-service:
    build: ./ms-auth-service
    container_name: ms-auth-service
    env_file:
      - ./ms-auth-service/.env
    ports:
      - "8001:8001"
    depends_on:
      - postgres-auth

volumes:
  auth_db_data: