services:

  # =========================
  # DATABASES
  # =========================

  db-auth:
    image: docker.io/deytonro/simcomp-auth-db:latest
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - simcomp-net

  db-personas:
    image: docker.io/deytonro/simcomp-personas-db:latest
    environment:
      POSTGRES_USER: ${PERSONAS_DB_USER}
      POSTGRES_PASSWORD: ${PERSONAS_DB_PASSWORD}
      POSTGRES_DB: ${PERSONAS_DB_NAME}
    volumes:
      - personas_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PERSONAS_DB_USER} -d ${PERSONAS_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - simcomp-net

  db-automotores:
    image: docker.io/deytonro/simcomp-automotores-db:latest
    environment:
      POSTGRES_USER: ${AUTOMOTORES_DB_USER}
      POSTGRES_PASSWORD: ${AUTOMOTORES_DB_PASSWORD}
      POSTGRES_DB: ${AUTOMOTORES_DB_NAME}
    volumes:
      - automotores_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTOMOTORES_DB_USER} -d ${AUTOMOTORES_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - simcomp-net

  db-infracciones:
    image: docker.io/deytonro/simcomp-infracciones-db:latest
    environment:
      POSTGRES_USER: ${INFRACCIONES_DB_USER}
      POSTGRES_PASSWORD: ${INFRACCIONES_DB_PASSWORD}
      POSTGRES_DB: ${INFRACCIONES_DB_NAME}
    volumes:
      - infracciones_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${INFRACCIONES_DB_USER} -d ${INFRACCIONES_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - simcomp-net

  db-comparendos:
    image: docker.io/deytonro/simcomp-comparendos-db:latest
    environment:
      POSTGRES_USER: ${COMPARENDOS_DB_USER}
      POSTGRES_PASSWORD: ${COMPARENDOS_DB_PASSWORD}
      POSTGRES_DB: ${COMPARENDOS_DB_NAME}
    volumes:
      - comparendos_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${COMPARENDOS_DB_USER} -d ${COMPARENDOS_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - simcomp-net

  # =========================
  # MICROSERVICIOS
  # =========================

  ms-auth-service:
    image: docker.io/deytonro/simcomp-auth-service:latest
    restart: always
    depends_on:
      db-auth:
        condition: service_healthy
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      AUTH_DB_HOST: db-auth
      AUTH_DB_PORT: 5432
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      AUTH_DB_USER: ${AUTH_DB_USER}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      PERSONAS_SERVICE_URL: http://ms-personas:8002
    volumes:
      - ./backend/ms-auth-service/src:/app/src
    networks:
      - simcomp-net

  ms-personas:
    image: docker.io/deytonro/simcomp-personas-service:latest
    restart: always
    depends_on:
      db-personas:
        condition: service_healthy
    volumes:
      - ./backend/ms-personas/src:/app/src
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      PERSONAS_DB_HOST: db-personas
      PERSONAS_DB_PORT: 5432
      PERSONAS_DB_NAME: ${PERSONAS_DB_NAME}
      PERSONAS_DB_USER: ${PERSONAS_DB_USER}
      PERSONAS_DB_PASSWORD: ${PERSONAS_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_SERVICE_URL: http://ms-auth-service:8001
      AUTOMOTORES_SERVICE_URL: http://ms-automotores:8003
      COMPARENDOS_SERVICE_URL: http://ms-comparendos:8005
    networks:
      - simcomp-net

  ms-automotores:
    image: docker.io/deytonro/simcomp-automotores-service:latest
    restart: always
    depends_on:
      db-automotores:
        condition: service_healthy
      ms-personas:
        condition: service_started
    ports:
      - "8003:8003"
    environment:
      PORT: 8003
      AUTOMOTORES_DB_HOST: db-automotores
      AUTOMOTORES_DB_PORT: 5432
      AUTOMOTORES_DB_NAME: ${AUTOMOTORES_DB_NAME}
      AUTOMOTORES_DB_USER: ${AUTOMOTORES_DB_USER}
      AUTOMOTORES_DB_PASSWORD: ${AUTOMOTORES_DB_PASSWORD}
      PERSONAS_SERVICE_URL: http://ms-personas:8002
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend/ms-automotores/src:/app/src
    networks:
      - simcomp-net

  ms-infracciones:
    image: docker.io/deytonro/simcomp-infracciones-service:latest
    restart: always
    depends_on:
      db-infracciones:
        condition: service_healthy
    ports:
      - "8004:8004"
    environment:
      PORT: 8004
      INFRACCIONES_DB_HOST: db-infracciones
      INFRACCIONES_DB_PORT: 5432
      INFRACCIONES_DB_NAME: ${INFRACCIONES_DB_NAME}
      INFRACCIONES_DB_USER: ${INFRACCIONES_DB_USER}
      INFRACCIONES_DB_PASSWORD: ${INFRACCIONES_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend/ms-infracciones/src:/app/src
    networks:
      - simcomp-net

  ms-comparendos:
    image: docker.io/deytonro/simcomp-comparendos-service:latest
    restart: always
    depends_on:
      db-comparendos:
        condition: service_healthy
      ms-personas:
        condition: service_started
      ms-automotores:
        condition: service_started
      ms-infracciones:
        condition: service_started
    ports:
      - "8005:8005"
    environment:
      PORT: 8005
      COMPARENDOS_DB_HOST: db-comparendos
      COMPARENDOS_DB_PORT: 5432
      COMPARENDOS_DB_NAME: ${COMPARENDOS_DB_NAME}
      COMPARENDOS_DB_USER: ${COMPARENDOS_DB_USER}
      COMPARENDOS_DB_PASSWORD: ${COMPARENDOS_DB_PASSWORD}
      PERSONAS_SERVICE_URL: http://ms-personas:8002
      AUTOMOTORES_SERVICE_URL: http://ms-automotores:8003
      INFRACCIONES_SERVICE_URL: http://ms-infracciones:8004
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend/ms-comparendos/src:/app/src
    networks:
      - simcomp-net

  ms-reportes:
    image: docker.io/deytonro/simcomp-reportes-service:latest
    restart: always
    depends_on:
      ms-auth-service:
        condition: service_started
      ms-personas:
        condition: service_started
      ms-automotores:
        condition: service_started
      ms-infracciones:
        condition: service_started
      ms-comparendos:
        condition: service_started
    ports:
      - "8006:8006"
    environment:
      PORT: 8006
      AUTH_SERVICE_URL: http://ms-auth-service:8001
      PERSONAS_SERVICE_URL: http://ms-personas:8002
      AUTOMOTORES_SERVICE_URL: http://ms-automotores:8003
      INFRACCIONES_SERVICE_URL: http://ms-infracciones:8004
      COMPARENDOS_SERVICE_URL: http://ms-comparendos:8005
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend/ms-reportes/src:/app/src
    networks:
      - simcomp-net

  # =========================
  # LOAD BALANCER (HAPROXY)
  # =========================

  haproxy:
    image: docker.io/deytonro/simcomp-haproxy-balance:latest
    volumes:
      - ./provisioning_docker/haproxy/haproxy.local.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8080:8080"
      - "8404:8404"
    depends_on:
      - ms-auth-service
      - ms-personas
      - ms-automotores
      - ms-infracciones
      - ms-comparendos
      - ms-reportes
      - frontend1
      - frontend2
    networks:
      - simcomp-net

  # =========================
  # FRONTEND
  # =========================

  frontend1:
    image: docker.io/deytonro/simcomp-frontend:latest
    restart: unless-stopped
    environment:
      API_URL: http://127.0.0.1:8080/api
    networks:
      - simcomp-net

  frontend2:
    image: docker.io/deytonro/simcomp-frontend:latest
    restart: unless-stopped
    environment:
      API_URL: http://127.0.0.1:8080/api
    networks:
      - simcomp-net

  ms-analytics-spark:
    image: docker.io/deytonro/simcomp-analytics-spark-service:latest
    restart: always
    ports:
      - "8010:8010"
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8010
      SPARK_MASTER_URL: local[*]
    volumes:
      - ./analytics-spark-service/data:/app/data
    networks:
      - simcomp-net

networks:
  simcomp-net:
    driver: bridge

volumes:
  auth_db_data:
  personas_db_data:
  automotores_db_data:
  infracciones_db_data:
  comparendos_db_data:
