version: "3.8"

services:
  ms-auth-service:
    build: ./ms-auth-service
    ports:
      - "8001:8001"

  ms-personas:
    build: ./ms-personas
    ports:
      - "8002:8002"

  ms-automotores:
    build: ./ms-automotores
    ports:
      - "8003:8003"

  ms-infracciones:
    build: ./ms-infracciones
    ports:
      - "8004:8004"

  ms-comparendos:
    build: ./ms-comparendos
    ports:
      - "8005:8005"