# =============================================================================
# SIMCOMP — Variables para el rol server-dns (svr-dns 192.168.100.2)
# =============================================================================

# IP de los servidores
dns_ip: 192.168.100.2
web_ip: 192.168.100.4
api_ip: 192.168.100.4
auth_ip: 192.168.100.3
per_ip: 192.168.100.3
veh_ip: 192.168.100.3
inf_ip: 192.168.100.3
cmp_ip: 192.168.100.3

# Configuración de UFW
ufw_allow_ports:
  - { port: 53, proto: tcp }
  - { port: 53, proto: udp }
  - { name: OpenSSH }

# Configuración de zonas DNS
dns_zone:
  direct:
    simcomp.co:
      ns: "{{ dns_ip }}"
      records:
        "@": "{{ web_ip }}"
        "www": "{{ web_ip }}"
        "api": "{{ api_ip }}"
        "auth": "{{ auth_ip }}"
        "per": "{{ per_ip }}"
        "veh": "{{ veh_ip }}"
        "inf": "{{ inf_ip }}"
        "cmp": "{{ cmp_ip }}"
        "dns": "{{ dns_ip }}"
  reverse:
    "100.168.192.in-addr.arpa":
      ns: "{{ dns_ip }}"
      ptrs:
        10: "{{ dns_ip }}"
        11: "{{ auth_ip }}"
        12: "{{ per_ip }}"
        13: "{{ veh_ip }}"
        14: "{{ inf_ip }}"
        15: "{{ cmp_ip }}"
        20: "{{ web_ip }}"